import { Toaster } from '@utima/ui';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { Layout } from '@/components/layout';
import { ThemeSwitcher } from '@/components/theme-switcher/theme-switcher';
import { ThemeProvider } from '@/contexts/theme-provider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <ThemeSwitcher />
          <Toaster />
          <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
