name: CI

on:
  push:
    branches: [$default-branch, main]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        shell: bash
        run: npm ci --ignore-scripts

      - name: 🚀 Turbo
        run: npx turbo run lint build test

      - name: Deploy
        if: endsWith(github.ref, 'main')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx changeset publish --no-git-tag

  deploy-storybook:
    needs: [ci]
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outcome.page_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'npm'

      - name: Build storybook
        run: npm run storybook:build --workspace=@utima/ui

      - name: Upload storybook artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: ./packages/ui/storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: storybook-static
