name: CI

on:
  push:
    branches: [$default-branch, main, next]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - name: Nx
        run: npx nx affected -t build lint test --parallel=3

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish
        if: endsWith(github.ref, 'main') || endsWith(github.ref, 'next')
        run: pnpm exec changeset publish --no-git-tag

      - name: Build storybook
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: pnpm --filter @utima/ui storybook:build

      - name: Fix permissions
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          chmod -c -R +rX "./packages/ui/storybook-static/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        id: upload
        with:
          path: ./packages/ui/storybook-static

  deploy-storybook:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://utima-solutions.github.io/ui
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
