name: CI

on:
  push:
    branches: [$default-branch, main]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        shell: bash
        run: npm ci --ignore-scripts

      - name: 🚀 Turbo
        run: npx turbo run lint build test

      - name: Publish
        if: endsWith(github.ref, 'main')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx changeset publish --no-git-tag

      - name: Build storybook
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npm run storybook:build --workspace=@utima/ui

      - name: Fix permissions
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          chmod -c -R +rX "./packages/ui/storybook-static/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        id: upload
        with:
          path: ./packages/ui/storybook-static

  deploy-storybook:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
