name: Deploy Storybook

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outcome.page_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        shell: bash
        run: npm ci --ignore-scripts

      - name: Build storybook
        run: npm run storybook:build --workspace=@utima/ui

      - name: Fix permissions
        run: |
          chmod -c -R +rX "./packages/ui/storybook-static/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        id: upload
        with:
          path: ./packages/ui/storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
